eliminate race, deadlock and dead code
adobe-apiplatform/api-gateway-config-supervisor pull request #3
Opened 2016-09-21 00:16 UTC by jkt628

2016-09-21 00:27 UTC, ddragosd commented
thanks @jkt628 . We'll be reviewing this soon.

2016-09-27 15:10 UTC, jkt628 commented
ping

2016-09-30 00:23 UTC, ddragosd commented on Makefile
> +DOCKER_TEMP := $(shell mktemp -u ./.Dockerfile.XXXXXXXXXX)
The intent here is to provide a `debug` configuration option when building the docker container ?

2016-09-30 16:00 UTC, jkt628 commented
no, this is a little preprocessing magic on Dockerfile to speed up development with complex builds.  by default it combines RUN commands into a single layer to decrease container size.  however, define DOCKER_BUILD_DEBUG and those commands go into separate layers which has the possibility to reuse docker cache, saving some time here and there.

2016-09-30 23:38 UTC, ddragosd commented
thanks for clarifying @jkt628 . I very much like your idea of streamlining the local development by replacing subsequent `RUN` commands with `&&`.  I was thinking at extending your idea to communicate the intent a little clearer into the `Dockerfile`. This could be achieved maybe by writing a `SQUASH` instruction above the `RUN` command like in the following example:
```Dockerfile
RUN echo "I'm the firt layer"
#SQUASH
RUN echo "I'm a squashed layer and I belong to the first layer"

RUN echo "I'm a second layer"
```

In this case the final Docker container would have 2 layers. The first 2 `RUN` commands would be squashed into a single layer, and the 3rd `RUN` command would be placed in its own layer.

The question I have next is: how would this optimization work with Docker Hub builds ? Would we actually commit the generated `Dockerfile` as `Dockerfile.optimized` and instruct Docker Hub to build an image using that file instead of the `Dockerfile` ?

2016-09-30 23:47 UTC, ddragosd requested changes
@jkt628 would it too much to include 2 extra changes with this PR ?
1. add a unit test for the fix on commit 4cd7591 `when a new directory detected watch the entire subtree`
2. update the README to include the instructions for building the Docker container locally with the DEBUG flag

The other conversation on how to enable the Dockerfile optimization for Docker Hub could be updated on a separate PR. 

Let me know what you think.

2016-09-30 23:47 UTC, ddragosd commented on Dockerfile
> +RUN echo " cleaning up ... " \
This RUN command to clean up will add a 0 size layer to the docker image but it won't actually reduce its size IIRC. If we want to reduce the size we might have to put all commands into a single RUN instruction.

2016-09-30 23:47 UTC, ddragosd commented on sync/recursiveWatcher.go
> +	fsw     *fsnotify.Watcher
was this changed for clarity ? Or it wasn't behaving correctly ?

2016-09-30 23:47 UTC, ddragosd commented on sync/recursiveWatcher.go
> +						for _, folder := range Subfolders(event.Name) {
good catch. it would be great to add a unit test for this scenario as well.

2016-10-01 00:59 UTC, jkt628 commented
happy to oblige in all respects

2016-10-03 15:24 UTC, jkt628 commented
i thought about the SQUASH request this weekend and think a fully automated approach has greater reach with less effort.  developers generally will not add decorators they neither understand nor trust, assuming they know about it in the first place.  "just do it" applies to more than exercise.

the only good reason for additional layers is if you expect reuse across images which is best expressed by FROM.  this image is not a good candidate.

i welcome debate on this issue, thanks.

2016-10-04 20:30 UTC, jkt628 commented on sync/recursiveWatcher.go
> +	fsw     *fsnotify.Watcher
this changes RecursiveWatcher's nature from is_a fsnotify.Watcher to has_a fsnotify.Watcher, denying access to fsnotify.Watcher.Events which should prevent future races.

2016-10-04 22:00 UTC, ddragosd commented
@jkt628 re `SQUASH` I see your point to make it even simpler for a good cause.  I'm curios what your thoughts are on my other question

>how would this optimization work with Docker Hub builds ? Would we actually commit the generated Dockerfile as Dockerfile.optimized and instruct Docker Hub to build an image using that file instead of the Dockerfile ?

2016-10-04 22:39 UTC, jkt628 commented
On 2016-10-04 16:00, ddragosd wrote:
> how would this optimization work with Docker Hub builds ? Would we
> actually commit the generated Dockerfile as Dockerfile.optimized and
> instruct Docker Hub to build an image using that file instead of the
> Dockerfile ?

1. i am fairly new to the game so maybe i don't understand the process 
fully but i thought Docker Hub merely accepts your already built images 
and am not aware that it builds images itself.
2. the extant Dockerfile builds images, just not optimized.  the README 
already suggests our preferred method and that builds optimized images. 
i think that is sufficient.

:{)}

2016-10-04 22:51 UTC, ddragosd commented
yes, one can build the image separately and then push it to Docker Hub.

Another easier way is to let Docker Hub automatically build the docker image on every git-push.
The UI looks like this: 
![image](https://cloud.githubusercontent.com/assets/541933/19095391/2ae0a8ee-8a4a-11e6-96a0-8cebc1d6acc6.png)

This is the case I was talking about in which the repo has to have an optimized dockerfile somewhere.

2016-10-11 21:54 UTC, jkt628 commented
i played with Docker Hub Automated Build and agree mine is not a good solution as Dockerfile is essentially a reserved word.  i will submit optimized Dockerfile for this PR and the upcoming PR for apigateway and later design a different approach for developers.

2016-10-11 23:04 UTC, jkt628 commented
@ddragosd these commits should address these issues:

1. add a unit test for the fix on commit 4cd7591 when a new directory detected watch the entire subtree
2. Another easier way is to let Docker Hub automatically build the docker image on every git-push

this issue no longer applies:

1. update the README to include the instructions for building the Docker container locally with the DEBUG flag

2016-10-11 23:12 UTC, jkt628 commented
this merge requires a new tag so i can submit a PR for [apigateway](https://github.com/adobe-apiplatform/apigateway)

2016-10-11 23:17 UTC, ddragosd commented
thanks @jkt628 . I'm checking the changes right now. 

>this merge requires a new tag so i can submit a PR for apigateway

I can help with making a new release as soon as we merge these changes.

BTW, we can also use commit SHAs to download tarballs even if we don't have a tag. i.e.
 https://github.com/adobe-apiplatform/api-gateway-config-supervisor/archive/05fcbb5.tar.gz

This might help with local testing once we commit something on a branch.

2016-10-11 23:24 UTC, ddragosd approved these changes

2016-10-11 23:24 UTC, ddragosd commented
👍

2016-10-11 23:27 UTC, merged

2016-10-11 23:30 UTC, ddragosd commented
@jkt628 I've drafted a new release candidate here: https://github.com/adobe-apiplatform/api-gateway-config-supervisor/releases/tag/1.0.1-RC1

2016-10-11 23:38 UTC, jkt628 commented
thanks for the quick response @ddragosd .  i think api-gateway-config-supervisor is not used by itself so will test via updates to apigateway.